version: "3"

networks:
  powerviz_network:
    name: powerviz_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24

services:
  powerviz_db:
    container_name: powerviz_db
    image: postgres:15.5-alpine
    networks:
      powerviz_network:
        ipv4_address: 172.27.0.10
    env_file:
      - .env
    hostname: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts/init-miso.sql:/docker-entrypoint-initdb.d/init-miso.sql
    ports:
      - 5433:5432

  powerviz_app:
    container_name: powerviz_app
    image: powerviz:latest
    networks:
        powerviz_network:
          ipv4_address: 172.27.0.20
    build: $PWD
    env_file:
      - .env
    ports:
      - ${POWERVIZ_PORT}:${POWERVIZ_PORT}
    depends_on:
      - powerviz_db
    volumes:
      - ./powerviz:/powerviz/powerviz
      - ./app:/powerviz/app
    restart: always
